CUDA_VISIBLE_DEVICES=$1 python3 train_vq.py \
--batch-size 32 \
--lr 6e-4 \
--total-iter 75000 \
--lr-scheduler 50000 \
--warm-up-iter 1000 \
--print-iter 100 \
--nb-code 128 \
--down-t 2 \
--depth 3 \
--dilation-growth-rate 3 \
--width 128 \
--output-emb-width 128 \
--code-dim 128 \
--out-dir output \
--dataname t2m \
--vq-act relu \
--quantizer ema_reset \
--loss-vel 0.5 \
--recons-loss l1_smooth \
--exp-name VQVAE_loc3d_train_mini
# --resume-pth output/VQVAE/net_best_fid.pth