CUDA_VISIBLE_DEVICES=$1 python3 train_vq.py \
--batch-size 256 \
--split train \
--lr 2e-4 \
--eval-iter 5000 \
--total-iter 300000 \
--lr-scheduler 200000 \
--nb-code 512 \
--down-t 2 \
--depth 3 \
--dilation-growth-rate 3 \
--out-dir output \
--dataname t2m \
--vq-act relu \
--quantizer ema_reset \
--loss-vel 0.5 \
--recons-loss l1_smooth \
--exp-name VQVAE_abs